baseURL = "https://examplesite.com"
googleAnalytics = ""
theme = "TFG"
title = "TFG "
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "+ Recursos"
pre = "#"
url = "carrer"
weight = "6"
[[menu.main]]
name = "Discusión y Conclusión"
pre = "#"
url = "contact"
weight = 5
[[menu.main]]
name = "Resultados"
pre = "#"
url = "products"
weight = 4
[[menu.main]]
name = "Metodología"
pre = "#"
url = "vision"
weight = 3
[[menu.main]]
name = "Introducción"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "TFG"
pre = ""
url = "/"
weight = 1
[params]
author = "Themefisher"
contact_info = ""
description = "This is meta description"
logo = "images/logo.png"
logo_width = "120px"
preloader = false
social = []
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = ""
map_center_lat = ""
map_center_lng = ""
map_marker = ""
map_position_lat = ""
map_position_lng = ""
