baseURL = "https://examplesite.com"
googleAnalytics = ""
theme = "omega"
title = "TFG "
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "TFG"
pre = ""
url = "/"
weight = 1
[[menu.main]]
name = "Introducción"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "Metodología"
pre = "#"
url = "vision"
weight = "3"
[[menu.main]]
name = "Resultados"
pre = "#"
url = "products"
weight = "4"
[[menu.main]]
name = "Discusión"
pre = "#"
url = "career"
weight = "5"
[[menu.main]]
name = "Conclusión"
pre = "#"
url = "contact"
weight = "6"
[params]
author = "Themefisher"
contact_info = "1001 Brickell bay <br>Dr. Miami, <br>FL 33131"
description = "This is meta description"
logo = "images/logo.png"
logo_width = "120px"
preloader = true
social = []
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_marker = "images/map-marker.png"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
